name: Deploy Utemy BE to Cloud Foundry
on:
  push:
    branches: [deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: ls backend
      - run: cat backend/manifest.yml
      - uses: jhunt/cf-push@main
        with:
          api: ${{ secrets.CF_API }}
          org: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: /github/workspace/backend/manifest.yml
          validate: false
